dist: bionic
sudo: false
language: elixir
elixir:
  - 1.9.4
  - 1.9.3
  - 1.9.2
  - 1.9.1
  - 1.9.0
  - 1.8.2
  - 1.8.1
  - 1.8.0
otp_release:
  - 22.2
  - 22.1
  - 22.0
  - 21.3
  - 21.2
  - 21.1
  - 21.0
before_script: git submodule update --init
matrix:
  include:
    - install:
        - mix local.rebar --force
        - mix local.hex --force
      script:
        - mix format --check-formatted --dry-run
        - mix credo --strict
    - secure: fpg2leA+GSEcbW+B9lkUPFHAsPoiq9VIF48izB4anR65TZgPIHoy7W04Ly+cHSDuPYPxxtCuZW5YU5ZBi3GAXNLsKZG3uTaoLQj+atZsDdyZNW7Z7Df2uVm3eIK7wC7XojalNtShYx56xTC19xrH01n6VouAcbgJ3TIfxQCraDk=
      script: mix coveralls.travis
