version: 2.1

executors:
  elixir:
    docker:
      - image: circleci/elixir:1.9.4
        environment:
          MIX_ENV: test

jobs:
  build:
    executor: elixir
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}
            - v1-mix-cache-{{ .Environment.OTP_VERSION }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-deps-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-deps-cache-{{ .Branch }}
            - v1-deps-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix archive.install hex bunt '~> 0.2' --force
      - run: mix archive.install hex credo '~> 1.1' --force
      - run: mix do deps.get
      - run: mix deps.compile

      - run: mix compile
      - run: mix dialyzer --plt

      - save_cache:
          key: v1-mix-cache-{{ .Environment.OTP_VERSION }}-{{ .Environment.ELIXIR_VERSION }}
          paths:
            - ~/.mix
      - save_cache:
          key: v1-mix-cache-{{ .Environment.OTP_VERSION }}
          paths:
            - ~/.mix
      - save_cache:
          key: v1-mix-cache
          paths:
            - ~/.mix

      - save_cache:
          key: v1-deps-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps
      - save_cache:
          key: v1-deps-cache-{{ .Branch }}
          paths:
            - deps
      - save_cache:
          key: v1-deps-cache
          paths:
            - deps

      - save_cache:
          key: v1-build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - _build
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - _build
      - save_cache:
          key: v1-build-cache
          paths:
            - _build

  format:
    executor: elixir
    steps:
      - checkout
      - run: mix format --check-formatted

  credo:
    executor: elixir
    steps:
      - checkout
      - run: mix credo --strict

  dialyzer:
    executor: elixir
    steps:
      - checkout
      - run: mix dialyzer --halt-exit-status

  test:
    executor: elixir
    steps:
      - checkout
      - run: mix coveralls.circleci
      - store_test_results:
          path: _build/test/lib/poison
      - store_artifacts:
          path: cover

  docs:
    executor: elixir
    steps:
      - checkout
      - run: mix docs
      - store_artifacts:
          path: doc

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - format:
          requires:
            - build
      - credo:
          requires:
            - build
      - dialyzer:
          requires:
            - build
      - test:
          requires:
            - build
      - docs:
          requires:
            - build
